version: '3'
services:
  couchdb:
    image: couchdb:3
    environment:
      - COUCHDB_PASSWORD=password
      - COUCHDB_USER=admin
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - db_data:/opt/couchdb/data
volumes:
  db_data: